6

I am creating a new GitHub Action workflow in my repository with the pull_request_target trigger on the closing of a pull request (to clean up allocated resources) from a branch to master. But it isn't triggering when I close the pull request (using the close pull request button in GitHub). I can't find what I'm doing wrong with my action
